language: node_js

node_js:
  - '6'

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  local_dir: _build
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the https://travis-ci.org/cvan/blog/settings dashboard.
  on:
    branch: master
  name: Cvan-o-matic-o-tron

