#!/usr/bin/env python

import codecs
import datetime
import os
import re
import sys

from markdown import markdown


def template(raw, values):
    def replace(match):
        item = match.group(1)
        return values.get(item, '<!-- empty %s -->' % item)
    return re.sub(r'\{\{ ?([a-zA-Z_]+) ?\}\}', replace, raw)


def get_data(content, filename):
    title = filename
    title_matches = re.search('# .+', content)
    if title_matches:
        title = title_matches.group(0)[2:]
    elif filename.endswith(('.markdown', '.md')):
        title = filename[:-3].replace('_', ' ')
        # Title case
        title = ' '.join(
            x[0].upper() + x[1:] for i, x in enumerate(title.split(' ')) if
            x.lower() not in ('a', 'of', 'the') or not i)

    year, month, date = map(int, filename.split('-')[:3])
    created = datetime.datetime(year, month, date)

    return {
        'title': title,
        'created': created.strftime('%d %b %Y').replace(' 0', ' ')
                                               .lstrip('0'),
        'created_date': created.strftime('%a %b %d %H:%M:%S %Y'),
        'url': '%s.html' % filename.rsplit('.', 1)[0],
    }


def open_file(*args, **kw):
    kw['mode'] = kw.get('mode', 'r')
    kw['encoding'] = kw.get('encoding', 'utf-8')
    return codecs.open(*args, **kw)


def read_file(*args, **kw):
    return open_file(*args, **kw).read()


header = read_file('templates/header.html')
footer = read_file('templates/footer.html')
list_header = read_file('templates/list_header.html')
list_item = read_file('templates/list_item.html')
list_footer = read_file('templates/list_footer.html')
article_header = read_file('templates/article_header.html')
article_footer = read_file('templates/article_footer.html')


def homepage_body():
    files = (x for x in os.listdir('.') if
             x.endswith('.md') and os.path.exists(x[:-2] + 'html'))

    filedata = []

    for f in files:
        post_body = read_file(f)
        filedata.append(get_data(post_body, f))

    posts = sorted(
        filedata, cmp=lambda a, b: cmp(a['created_date'], b['created_date']))
    posts = reversed(posts)
    return (list_header +
        u''.join(template(list_item, data) for data in posts) +
        list_footer)


def assemble(path=None):
    data = {}

    if path:
        path = os.path.basename(path)

        contents = read_file(path)
        data = get_data(contents, path)
        data['body'] = markdown(contents)
        data['title'] += u' | '

        output_header = header + article_header
        output_footer = article_footer + footer
    else:
        data['body'] = (homepage_body() or
            '<p class="empty">There aren\'t any posts here yet!</p>')
        data['title'] = u''

        output_header = header
        output_footer = footer

    data['page_type'] = 'item' if path else 'home'
    output = template(output_header + u'{{ body }}' + output_footer, data)

    outpath = path.rsplit('.', 1)[0] + '.html' if path else 'index.html'
    with open_file(outpath, mode='w', errors='xmlcharrefreplace') as outfile:
        print 'Writing to %s' % outpath
        outfile.write(output)


if __name__ == '__main__':
    if len(sys.argv) == 1:
        print 'No file specified.'
        sys.exit(1)
    to_open = sys.argv[1]
    if not os.path.exists(to_open):
        print 'Could not open "%s" for rendering.' % to_open
        sys.exit(1)
    assemble(to_open)  # Render article page.
    assemble()  # Render homepage.
